# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: filter_sync.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'filter_sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66ilter_sync.proto\x12\nfiltersync\"G\n\x18UpdateUserFiltersRequest\x12\r\n\x05tg_id\x18\x01 \x01(\x03\x12\x0e\n\x06\x66ilter\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"=\n\x19UpdateUserFiltersResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2u\n\x11\x46ilterSyncService\x12`\n\x11UpdateUserFilters\x12$.filtersync.UpdateUserFiltersRequest\x1a%.filtersync.UpdateUserFiltersResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'filter_sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_UPDATEUSERFILTERSREQUEST']._serialized_start=33
  _globals['_UPDATEUSERFILTERSREQUEST']._serialized_end=104
  _globals['_UPDATEUSERFILTERSRESPONSE']._serialized_start=106
  _globals['_UPDATEUSERFILTERSRESPONSE']._serialized_end=167
  _globals['_FILTERSYNCSERVICE']._serialized_start=169
  _globals['_FILTERSYNCSERVICE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
